services:
  elasticsearch: # Define the Elasticsearch service
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2 # Use the official Elasticsearch image from Docker Hub
    container_name: elasticsearch # Set a custom container name for Elasticsearch
    environment: # Set environment variables for Elasticsearch
      - discovery.type=single-node # Run Elasticsearch in single-node mode (useful for dev/test)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Limit the Java heap size to 512 MB (adjust based on your system)
      - xpack.security.enabled=false # Disable security (authentication) in Elasticsearch
    ports:
      - "9200:9200" # Expose port 9200 for Elasticsearch HTTP API (use to query data)
      - "9300:9300" # Expose port 9300 for Elasticsearch internal cluster communication
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persist Elasticsearch data in a named volume

  kibana: # Define the Kibana service
    image: docker.elastic.co/kibana/kibana:8.6.2 # Use the official Kibana image from Docker Hub
    container_name: kibana # Set a custom container name for Kibana
    environment: # Set environment variables for Kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200 # Connect Kibana to the Elasticsearch service
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Ensure Kibana uses the correct Elasticsearch host
      - xpack.security.enabled=false # Disable security (authentication) in Kibana
    ports:
      - "5601:5601" # Expose port 5601 for the Kibana web interface (default port for accessing Kibana)
    depends_on:
      - elasticsearch # Ensure Kibana starts after Elasticsearch is up and running

  filebeat: # Define the Filebeat service
    image: docker.elastic.co/beats/filebeat:8.6.2 # Use the official Filebeat image from Docker Hub
    container_name: filebeat # Set a custom container name for Filebeat
    user: root # Run Filebeat as root to access log files
    environment:
      - FILEBEAT_OUTPUT_LOGSTASH_HOST=logstash:5044 # Send logs to Logstash
    depends_on:
      - logstash # Ensure Filebeat starts after Logstash is up and running
    command: |
      filebeat -e \
        -E output.logstash.enabled=true \
        -E output.logstash.hosts=["logstash:5044"] \
        -E filebeat.config.modules=path.config=/etc/filebeat/modules.d

  logstash: # Define the Logstash service
    image: docker.elastic.co/logstash/logstash:8.6.2 # Use the official Logstash image from Docker Hub
    container_name: logstash # Set a custom container name for Logstash
    environment:
      - LOGSTASH_INPUT_BEATS_PORT=5044 # Configure Logstash to listen on port 5044 for Filebeat input
    ports:
      - "5044:5044" # Expose port 5044 for Filebeat communication
    depends_on:
      - elasticsearch # Ensure Logstash starts after Elasticsearch is up and running
    command: |
      logstash -e "input { beats { port => 5044 } } output { elasticsearch { hosts => ['http://elasticsearch:9200'] } }"

volumes:
  esdata: # Define the persistent volume for Elasticsearch data
    driver: local # Use a local driver for the volume (can be changed based on needs)
