filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /path/to/your/log/file.log  # Path to the log file you want to ship

output.logstash:
  hosts: ["127.0.0.1:5044"]  # Replace with your Logstash host and port
  # Optional: Uncomment to configure authentication with Logstash
  # username: "logstash-user"
  # password: "logstash-password"
